server:
  port: 8082
spring:
  application:
    name: cmdb-task
  dubbo:
    application:
      name: cmdb-task    
    registry:
      address: zookeeper://127.0.0.1:2181   
    protocol:
      name: dubbo    
      port: 20880
    scan:
      com.cmdb.service
    monitor:
      protocal: registry
  zipkin:
    enabled: true
     # zipkkin dashboard的地址：通过真实IP地址访问
    baseUrl: http://localhost:17601/
     # 通过cloud-dashboard-zipkin注册到注册中心的服务名称访问，本版本(spring-cloud-sleuth-core-1.2.5.RELEASE)不支持，需要从spring-cloud-sleuth-core-1.3.0.RELEASE开始支持这个功能
     # 配置如下：
     # baseUrl: http://cloud-dashboard-zipkin/
  sleuth:
    sampler:
       #  默认值为0.1f，现在为了测试设置100%采集
      percentage: 1
logging:
  level:
    root: INFO
    com.cmdb: DEBUG
    
  