server:
  port: 8080
spring:
  application:
    name: cmdb-task
logging:
  level:
    root: INFO
    com.cmdb: DEBUG
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka,http://peer1:8761/eureka,http://peer1:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5