server:
  port: 8888
spring:
  application:
    name: cmdb-admin
  profiles:
    active: "insecure"
   
eureka:
  instance:
    health-check-url-path: /actuator/health
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka,http://eureka1:8762/eureka,http://eureka1:8763/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details:  ALWAYS
      
---
spring:
  profiles: insecure
         
         
---
spring:
  profiles: secure
  security:
    user:
      name: "admin"
      password: "admin"