server:
  port: 8081
spring:
  application:
    name: cmdb-web
  zipkin:
    enabled: true
     # zipkkin dashboard的地址：通过真实IP地址访问
    baseUrl: http://zipkin-server:17601/
     # 通过cloud-dashboard-zipkin注册到注册中心的服务名称访问，本版本(spring-cloud-sleuth-core-1.2.5.RELEASE)不支持，需要从spring-cloud-sleuth-core-1.3.0.RELEASE开始支持这个功能
     # 配置如下：
     # baseUrl: http://cloud-dashboard-zipkin/
  sleuth:
    sampler:
       #  默认值为0.1f，现在为了测试设置100%采集
      percentage: 1
  main:
    allow-bean-definition-overriding: true
      
logging:
  level:
    root: INFO
    com.cmdb: DEBUG
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka,http://eureka3:8763/eureka
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5